### ISSUE TITLE
Doesn't seem to connect

### ISSUE THREAD

**Issue by CharlesJQuarra** [lenaten/headless-chrome#1]
I setup the docker image as described, run the 'open' command, and I got a 'cannot connect' error in the browser: 

This site can’t be reached

localhost refused to connect.
Search Google for localhost 9222
ERR_CONNECTION_REFUSED

Running on mac os x 10.10. Docker ps shows the image running, and when I enter inside the docker instance and run a ps auxww, chrome seems to be running:

 >ps axuww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.3  3.3 560136 69436 ?        Ssl  16:09   0:00 /usr/bin/google-chrome --headless --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 https://www.google.com
root        10  0.0  0.0   4536   672 ?        S    16:09   0:00 cat
root        11  0.0  0.0   4536   784 ?        S    16:09   0:00 cat
root        14  0.0  1.8 342444 38232 ?        S    16:09   0:00 /opt/google/chrome/chrome --type=zygote --headless --headless
root        16  0.0  0.5 342444 10344 ?        S    16:09   0:00 /opt/google/chrome/chrome --type=zygote --headless --headless
root        33  0.6  5.1 761556 104604 ?       Sl   16:09   0:01 /opt/google/chrome/chrome --type=renderer --use-gl=osmesa --disable-databases --primordial-pipe-token=9C6F1C59EBAA92FC2297C3A6A0F96830 --lang=en-US --headless --enable-pinch --num-raster-threads=1 --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1
root        49  1.0  0.1  18244  3348 ?        Ss   16:13   0:00 bash
root        57  0.0  0.1  34424  2908 ?        R+   16:13   0:00 ps axuww

**Comment by lenaten** [comment]
this works now?
